### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by Drixevel** [floydpink/atom-compare-files#7] opened 2015-01-22 08:26 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (c:\Users\Keith\AppData\Local\atom\app-0.175.0\resources\app\src\atom.js:55:11)
Object.activate (c:\Users\Keith\.atom\packages\compare-files\lib\compare-files.js:75:14)
```

I don't like posting messages with automation but here ya go.

**Comment by floydpink** [comment] 2015-01-22 16:05
Duplicate of #6

**Closed by floydpink** 2015-01-22 16:05 UTC
Labels: duplicate
