### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by sunnyg522** [floydpink/atom-compare-files#9] opened 2015-02-04 18:54 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Users/dgunda/Downloads/Atom.app/Contents/Resources/app/src/atom.js:55:11)
setStatusMessage (/Users/dgunda/.atom/packages/compare-files/lib/compare-files.js:23:7)
```

**Comment by sunnyg522** [comment] 2015-02-04 18:55
I am unable to compare file which are in diff directors.

**Comment by floydpink** [comment] 2015-02-05 00:54
The original issue raised here is duplicate of #6 and is resolved in the latest published version

**Closed by floydpink** 2015-02-05 00:54 UTC
