### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by gcornejo** [floydpink/atom-compare-files#8] opened 2015-01-26 13:47 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
Object.activate (/Users/admin/Dropbox/Mackup/.atom/packages/compare-files/lib/compare-files.js:75:14)
```

**Comment by floydpink** [comment] 2015-01-26 14:46
Duplicate of #6. Install the latest version and this should be fixed.

**Closed by floydpink** 2015-01-26 14:46 UTC
Labels: duplicate
